// <auto-generated />
using CriandoWebApiAlunos.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CriandoWebApiAlunos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240225151603_PopulaTabela")]
    partial class PopulaTabela
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CriandoWebApiAlunos.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "joana.penha_darc@yahoo.com",
                            Idade = 15,
                            Nome = "Joana Darc da Penha"
                        },
                        new
                        {
                            Id = 2,
                            Email = "fernando.luislima@yahoo.com",
                            Idade = 17,
                            Nome = "Fernando Luís de Lima"
                        },
                        new
                        {
                            Id = 3,
                            Email = "mariana.silva.santos@gmail.com",
                            Idade = 16,
                            Nome = "Mariana Silva Santos"
                        },
                        new
                        {
                            Id = 4,
                            Email = "pedro.henrique.oliveira@hotmail.com",
                            Idade = 18,
                            Nome = "Pedro Henrique Oliveira"
                        },
                        new
                        {
                            Id = 5,
                            Email = "ana.clara.souza@outlook.com",
                            Idade = 15,
                            Nome = "Ana Clara Souza"
                        },
                        new
                        {
                            Id = 6,
                            Email = "bruno.cesar.costa@uol.com.br",
                            Idade = 19,
                            Nome = "Bruno César Costa"
                        },
                        new
                        {
                            Id = 7,
                            Email = "julia.martins.rocha@gmail.com",
                            Idade = 16,
                            Nome = "Julia Martins Rocha"
                        },
                        new
                        {
                            Id = 8,
                            Email = "rafaela.dias.ferreira@hotmail.com",
                            Idade = 15,
                            Nome = "Rafaela Dias Ferreira"
                        },
                        new
                        {
                            Id = 9,
                            Email = "lucas.gabriel.souza@outlook.com",
                            Idade = 18,
                            Nome = "Lucas Gabriel Souza"
                        },
                        new
                        {
                            Id = 10,
                            Email = "gabriela.lima.santos@yahoo.com",
                            Idade = 17,
                            Nome = "Gabriela Lima Santos"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
